//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiaoBlog.Repository.EF
{
    using MiaoBlog.Model.Articles;
    using MiaoBlog.Model.ArticleTags;
    using MiaoBlog.Model.Categories;
    using MiaoBlog.Model.Comments;
    using MiaoBlog.Model.Tags;
    using MiaoBlog.Model.Users;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BlogEntities : DbContext
    {
        public BlogEntities()
            : base("name=BlogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Article> Blog_Article { get; set; }
        public DbSet<Category> Blog_Category { get; set; }
        public DbSet<Comment> Blog_Comment { get; set; }
        public DbSet<Tag> Blog_Tag { get; set; }
        public DbSet<Article_Tag> Blog_Article_Tag { get; set; }
        public DbSet<User> User { get; set; }
    }
}
